import React from "react"

export function PixelPomodoroPrivacy() {
  return (
    <div className="container mx-auto px-6 max-w-3xl py-32 pt-40">
      <h1 className="text-4xl font-bold tracking-tight mb-8">Privacy Policy for PixelPomodoro</h1>
      <div className="prose prose-invert max-w-none text-muted-foreground space-y-6">
        <p><strong>Effective Date: July 23, 2026</strong></p>
        
        <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">1. Overview</h2>
        <p>PixelPomodoro (&quot;we&quot;, &quot;our&quot;, or &quot;the extension&quot;) is a cozy pixel-art productivity timer Chrome extension designed to help users manage work and break intervals. We are committed to protecting your privacy. This Privacy Policy explains our practices regarding user information.</p>

        <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">2. Information Collection and Use</h2>
        <p>PixelPomodoro <strong className="text-foreground">does not collect, store, transmit, or share any personal data or usage analytics</strong>.</p>
        <p>All data generated by the extension—including:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Timer settings (work duration, break durations, auto-start options, sound preferences)</li>
          <li>Productivity statistics (daily completed pomodoros, streaks, best streaks)</li>
          <li>Unlocked achievements</li>
        </ul>
        <p>is stored <strong className="text-foreground">100% locally</strong> within your browser using Chrome&apos;s built-in local storage API (<code className="bg-muted px-1.5 py-0.5 rounded text-sm text-foreground">chrome.storage.sync</code>).</p>

        <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">3. Network &amp; External Connections</h2>
        <p>PixelPomodoro operates completely offline:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>No data is sent to external servers.</li>
          <li>No analytics, tracking scripts, or telemetry frameworks are included.</li>
          <li>No remote code is loaded or executed.</li>
        </ul>

        <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">4. Permissions</h2>
        <p>PixelPomodoro requests the following minimal browser permissions:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li><code className="bg-muted px-1.5 py-0.5 rounded text-sm text-foreground">storage</code>: Used solely to save user timer settings and statistics locally.</li>
          <li><code className="bg-muted px-1.5 py-0.5 rounded text-sm text-foreground">alarms</code>: Used to run background countdown timers so sessions remain accurate when the extension popup is closed.</li>
          <li><code className="bg-muted px-1.5 py-0.5 rounded text-sm text-foreground">notifications</code>: Used to display local desktop notifications when a work or break session completes.</li>
        </ul>

        <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">5. Third-Party Sharing</h2>
        <p>We do not sell, rent, trade, or share any user data with third parties under any circumstances.</p>

        <h2 className="text-2xl font-semibold text-foreground mt-8 mb-4">6. Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, please contact the developer via the Chrome Web Store support page or project repository.</p>
        <p><strong>Yogesh Parihar</strong></p>
        <p>Email: <strong><a href="mailto:yogeshparihar2105@gmail.com" className="text-primary hover:underline">yogeshparihar2105@gmail.com</a></strong></p>
      </div>
    </div>
  )
}
